### ISSUE TITLE
[Question] Will this project work on Linux ? 

### ISSUE THREAD

**Issue by ghost** [axmetishe/gradle-qt-application-example#1]
I asked this question because in [build.gradle][1] there are configurations for windows and mac.But , there is no configuration for Linux.

So , I have this doubt.

  [1]: https://github.com/axmetishe/gradle-qt-application-example/blob/master/build.gradle#L28#L77

**Comment by axmetishe** [comment]
I see.
There's nothing required for Linux configuration actually:)
QT toolchains for MacOS and Windows were extended from Linux because they need additional configuration for tools like resource compiler on Windows and dmg generations on MacOS.

So for the Linux we just need to have QT SDK and clang or gcc compiler installed.
QT SDK on Linux have two options for installation - from the qt installer bundle from their site and from native packages, both ways will work with that plugin since it looking for them in path and additional variable QT_PATH in case defined.

Regarding cpp toolchain it configured the way it defined at gradle-cpp-plugin and in the example app it set to the default when the Gradle is determined it by itself.

**Comment by axmetishe** [comment]
If you need to add some Linux specific compiler, linker or librarian arguments just use `(compileTask.targetPlatform.get().operatingSystem.isLinux())` or configure the toolchain.

After you have compiler and QT SDK installed just try to execute `./gradlew build` on example app.

**Comment by ghost** [comment]
This project is an example for a qt application. 

But , I want to make library like  [this][1].

How can I do this with this plugin ?


  [1]: https://youtu.be/ZewJ4iHQvXY

**Comment by axmetishe** [comment]
The same way as app, just use the cpp-library Gradle plugin https://docs.gradle.org/current/userguide/cpp_library_plugin.html

**Comment by ghost** [comment]
> If you need to add some Linux specific compiler, linker or librarian arguments just use `(compileTask.targetPlatform.get().operatingSystem.isLinux())` or configure the toolchain.
> 
> After you have compiler and QT SDK installed just try to execute `./gradlew build` on example app.

I can't understand. Can you explain this in detail?

**Comment by axmetishe** [comment]
Please follow gradle cpp-library plugin documentation.

**Comment by axmetishe** [comment]
Project is working on Windows, MacOS and Linux, please follow gradle-native examples for extending functionality.
